FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG PROJECT_PATH

WORKDIR /src
COPY . .

RUN dotnet restore "$PROJECT_PATH"
RUN dotnet publish "$PROJECT_PATH" -c Release -o /app/publish /p:UseAppHost=false /p:DebugSymbols=false /p:DebugType=None

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
ARG PROJECT_DLL
ENV PROJECT_DLL="$PROJECT_DLL"
ENV ASPNETCORE_URLS=http://+:8080

WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "dotnet \"$PROJECT_DLL\""]
